volumes:
  penggajian_kafka:

services:
  penggajian:
    container_name: Penggajian-Kafka
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    env_file:
      - .env
    volumes:
      - penggajian_kafka:/app/result_excel