volumes:
  penggajian_kafka:

services:
  penggajian_kafka:
    container_name: Penggajian-Kafka
    build: .
    ports:
      - "81:80"
    env_file:
      - .env
    volumes:
      - penggajian_kafka:/app/result_excel