[supervisord]
nodaemon=true

[program:fastapi]
command=uvicorn main:app --host 0.0.0.0 --port 80 --reload
autostart=true
autorestart=true
priority=10

[program:kafka-consumer]
command=python konsumer.py
autostart=true
autorestart=true
priority=20